# Generated by Django 2.2.28 on 2024-08-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='played',
            field=models.IntegerField(default=0),
        ),
    ]
